-- Auto-generated from catalogData.ts
insert into public.achievements_catalog (id, slug, title, description, category, subcategory, tier, target_value, sort_order)
values
  (1, 'speed_wpm_30', 'Walker', 'Reach 30 WPM in a single session.', 'velocidad', 'Speed Peaks', 'bronce', 30, 1),
  (2, 'speed_wpm_45', 'Trotter', 'Reach 45 WPM in a single session.', 'velocidad', 'Speed Peaks', 'bronce', 45, 2),
  (3, 'speed_wpm_60', 'Runner', 'Reach 60 WPM in a single session.', 'velocidad', 'Speed Peaks', 'plata', 60, 3),
  (4, 'speed_wpm_75', 'Swift', 'Reach 75 WPM in a single session.', 'velocidad', 'Speed Peaks', 'plata', 75, 4),
  (5, 'speed_wpm_90', 'Sprinter', 'Reach 90 WPM in a single session.', 'velocidad', 'Speed Peaks', 'oro', 90, 5),
  (6, 'speed_wpm_105', 'Surge', 'Reach 105 WPM in a single session.', 'velocidad', 'Speed Peaks', 'oro', 105, 6),
  (7, 'speed_wpm_120', 'Lightning', 'Reach 120 WPM in a single session.', 'velocidad', 'Speed Peaks', 'diamante', 120, 7),
  (8, 'speed_wpm_135', 'Hyperspeed', 'Reach 135 WPM in a single session.', 'velocidad', 'Speed Peaks', 'diamante', 135, 8),
  (9, 'speed_wpm_150', 'Supersonic', 'Reach 150 WPM in a single session.', 'velocidad', 'Speed Peaks', 'diamante', 150, 9),
  (10, 'speed_wpm_165', 'Photon', 'Reach 165 WPM in a single session.', 'velocidad', 'Speed Peaks', 'diamante', 165, 10),
  (11, 'speed_wpm_180', 'Tachyon', 'Reach 180 WPM in a single session.', 'velocidad', 'Speed Peaks', 'diamante', 180, 11),
  (12, 'speed_wpm_200', 'Rhythmic Singularity', 'Reach 200 WPM in a single session.', 'velocidad', 'Speed Peaks', 'especial', 200, 12),
  (13, 'speed_cruise_60', 'Cruise Speed I', 'Maintain an average WPM above 60 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'plata', 60, 13),
  (14, 'speed_cruise_70', 'Cruise Speed II', 'Maintain an average WPM above 70 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'plata', 70, 14),
  (15, 'speed_cruise_80', 'Cruise Speed III', 'Maintain an average WPM above 80 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'oro', 80, 15),
  (16, 'speed_cruise_90', 'Cruise Speed IV', 'Maintain an average WPM above 90 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'oro', 90, 16),
  (17, 'speed_cruise_100', 'Cruise Speed V', 'Maintain an average WPM above 100 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'diamante', 100, 17),
  (18, 'speed_cruise_110', 'Cruise Speed VI', 'Maintain an average WPM above 110 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'diamante', 110, 18),
  (19, 'speed_cruise_120', 'Cruise Speed VII', 'Maintain an average WPM above 120 in a full lesson or song.', 'velocidad', 'Sustained Speed', 'diamante', 120, 19),
  (20, 'speed_early_burst_100', 'Explosive Start', 'Reach 100 WPM within the first 5 seconds of a race.', 'velocidad', 'Speed Challenges', 'oro', 100, 20),
  (21, 'speed_sustain_80_300s', 'Steady Engine', 'Maintain 80+ WPM for 5 continuous minutes in a session.', 'velocidad', 'Speed Challenges', 'plata', 80, 21),
  (22, 'speed_peak_220', 'Event Horizon', 'Reach 220 WPM in a test-mode session.', 'velocidad', 'Speed Challenges', 'especial', 220, 22),
  (23, 'perfect_sessions_1', 'Clean Shot', 'Complete 1 session with 100% accuracy.', 'precision', 'Perfect Sessions', 'bronce', 1, 23),
  (24, 'perfect_sessions_5', 'Eagle Eye', 'Complete 5 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'bronce', 5, 24),
  (25, 'perfect_sessions_10', 'Surgeon', 'Complete 10 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'plata', 10, 25),
  (26, 'perfect_sessions_25', 'Surgical Precision', 'Complete 25 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'plata', 25, 26),
  (27, 'perfect_sessions_50', 'Machine', 'Complete 50 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'oro', 50, 27),
  (28, 'perfect_sessions_75', 'Automaton', 'Complete 75 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'oro', 75, 28),
  (29, 'perfect_sessions_100', 'Absolute Perfection', 'Complete 100 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'diamante', 100, 29),
  (30, 'perfect_sessions_250', 'Perfect Entity', 'Complete 250 sessions with 100% accuracy.', 'precision', 'Perfect Sessions', 'especial', 250, 30),
  (31, 'combo_max_50', 'Focus', 'Reach a 50-keystroke correct combo.', 'precision', 'Combos', 'bronce', 50, 31),
  (32, 'combo_max_100', 'Solid Chain', 'Reach a 100-keystroke correct combo.', 'precision', 'Combos', 'bronce', 100, 32),
  (33, 'combo_max_150', 'Flow', 'Reach a 150-keystroke correct combo.', 'precision', 'Combos', 'plata', 150, 33),
  (34, 'combo_max_200', 'Current', 'Reach a 200-keystroke correct combo.', 'precision', 'Combos', 'plata', 200, 34),
  (35, 'combo_max_300', 'Trance', 'Reach a 300-keystroke correct combo.', 'precision', 'Combos', 'oro', 300, 35),
  (36, 'combo_max_400', 'Zen State', 'Reach a 400-keystroke correct combo.', 'precision', 'Combos', 'oro', 400, 36),
  (37, 'combo_max_500', 'Unstoppable', 'Reach a 500-keystroke correct combo.', 'precision', 'Combos', 'diamante', 500, 37),
  (38, 'combo_max_750', 'Combo Titan', 'Reach a 750-keystroke correct combo.', 'precision', 'Combos', 'diamante', 750, 38),
  (39, 'combo_max_1000', 'Divine', 'Reach a 1000-keystroke correct combo.', 'precision', 'Combos', 'especial', 1000, 39),
  (40, 'precision_steady_hand_5', 'Steady Hand', 'Play 5 consecutive sessions without dropping below 98% accuracy.', 'precision', 'Consistency', 'plata', 5, 40),
  (41, 'precision_steady_hand_10', 'Steel Pulse', 'Play 10 consecutive sessions without dropping below 98% accuracy.', 'precision', 'Consistency', 'oro', 10, 41),
  (42, 'precision_recovery_100', 'Quick Recovery', 'Make a mistake and rebuild a 100-keystroke combo in the same session.', 'precision', 'Recovery', 'oro', 100, 42),
  (43, 'precision_recovery_200', 'Combo Phoenix', 'Make a mistake and rebuild a 200-keystroke combo in the same session.', 'precision', 'Recovery', 'diamante', 200, 43),
  (44, 'mp_wins_1', 'Contender', 'Win 1 multiplayer race.', 'multijugador', 'Victories', 'bronce', 1, 44),
  (45, 'mp_wins_5', 'Rival', 'Win 5 multiplayer races.', 'multijugador', 'Victories', 'bronce', 5, 45),
  (46, 'mp_wins_10', 'Gladiator', 'Win 10 multiplayer races.', 'multijugador', 'Victories', 'plata', 10, 46),
  (47, 'mp_wins_25', 'Arena Veteran', 'Win 25 multiplayer races.', 'multijugador', 'Victories', 'plata', 25, 47),
  (48, 'mp_wins_50', 'Champion', 'Win 50 multiplayer races.', 'multijugador', 'Victories', 'oro', 50, 48),
  (49, 'mp_wins_100', 'Dominator', 'Win 100 multiplayer races.', 'multijugador', 'Victories', 'diamante', 100, 49),
  (50, 'mp_wins_250', 'Conqueror', 'Win 250 multiplayer races.', 'multijugador', 'Victories', 'diamante', 250, 50),
  (51, 'mp_wins_500', 'Legend', 'Win 500 multiplayer races.', 'multijugador', 'Victories', 'especial', 500, 51),
  (52, 'mp_clutch_win', 'Clutch', 'Win a multiplayer race by less than 1 second.', 'multijugador', 'Race Feats', 'oro', 1, 52),
  (53, 'mp_dominant_win', 'Top Fragger', 'Win a race beating second place by more than 30 WPM.', 'multijugador', 'Race Feats', 'oro', 1, 53),
  (54, 'mp_grade_ss_win', 'Absolute Dominance', 'Win a multiplayer race with grade SS or SS+.', 'multijugador', 'Race Feats', 'diamante', 1, 54),
  (55, 'mp_win_streak_5', 'Undefeated', 'Win 5 multiplayer races in a row.', 'multijugador', 'Win Streaks', 'diamante', 5, 55),
  (56, 'mp_win_streak_10', 'Unstoppable Online', 'Win 10 multiplayer races in a row.', 'multijugador', 'Win Streaks', 'especial', 10, 56),
  (57, 'mp_comeback_win', 'Epic Comeback', 'Go from last place at the halfway point to first at the finish.', 'multijugador', 'Race Feats', 'especial', 1, 57),
  (58, 'mp_players_4', 'Crowded Room', 'Complete a multiplayer race with 4 or more players.', 'multijugador', 'Multiplayer Lobbies', 'plata', 4, 58),
  (59, 'mp_players_8', 'Crowd', 'Complete a multiplayer race with 8 players.', 'multijugador', 'Multiplayer Lobbies', 'diamante', 8, 59),
  (60, 'mp_win_full_lobby', 'King of the Arena', 'Win a multiplayer race with 4 or more players in the lobby.', 'multijugador', 'Multiplayer Lobbies', 'oro', 1, 60),
  (61, 'mp_photo_finish', 'Photo Finish', 'Win a multiplayer race by less than 0.5 seconds.', 'multijugador', 'Race Feats', 'diamante', 1, 61),
  (62, 'mod_sudden_death_win', 'Living on the Edge', 'Win a match with Sudden Death enabled.', 'riesgo', 'Modifiers', 'oro', 1, 62),
  (63, 'mod_blind_95', 'Pure Muscle Memory', 'Finish a Blind Mode session with over 95% accuracy.', 'riesgo', 'Modifiers', 'oro', 95, 63),
  (64, 'mod_strict_grade_s', 'Merciless Keyboard', 'Complete a Strict session (no backspace) with grade S or higher.', 'riesgo', 'Modifiers', 'diamante', 1, 64),
  (65, 'mod_flashlight_complete', 'Tunnel Vision', 'Complete a race with the Flashlight modifier enabled.', 'riesgo', 'Modifiers', 'plata', 1, 65),
  (66, 'mod_vampire_survive', 'Survivor', 'Win a Vampire match finishing with less than 10% HP.', 'riesgo', 'Modifiers', 'diamante', 1, 66),
  (67, 'mod_double_time_grade_a', 'Adrenaline', 'Complete a song with Double Time at grade A or higher.', 'riesgo', 'Modifiers', 'oro', 1, 67),
  (68, 'mod_rhythm_lock_perfect', 'Human Metronome', 'Complete a song with Rhythm Lock without breaking combo from drift.', 'riesgo', 'Modifiers', 'diamante', 1, 68),
  (69, 'mod_masocore', 'Masocore', 'Finish a match with Sudden Death, Blind Mode, and Flashlight active together.', 'riesgo', 'Modifiers', 'especial', 1, 69),
  (70, 'tech_left_hand_perfect', 'Vowels Mastered', '100% accuracy on left-hand keys (A, O, E, U, I) in a full session.', 'tecnica', 'Technique', 'oro', 1, 70),
  (71, 'tech_right_hand_perfect', 'Lethal Consonants', '100% accuracy on right-hand keys in a full session.', 'tecnica', 'Technique', 'oro', 1, 71),
  (72, 'tech_dev_symbols_ss', 'Clean Code', 'Complete the developer symbols lesson with grade SS.', 'tecnica', 'Technique', 'diamante', 1, 72),
  (73, 'tech_custom_code_s', 'SysAdmin', 'Finish a custom practice session with real source code at grade S or higher.', 'tecnica', 'Technique', 'oro', 1, 73),
  (74, 'streak_days_3', 'Habit', 'Practice 3 days in a row.', 'resistencia', 'Daily Streaks', 'bronce', 3, 74),
  (75, 'streak_days_7', 'Discipline', 'Practice 7 days in a row.', 'resistencia', 'Daily Streaks', 'plata', 7, 75),
  (76, 'streak_days_14', 'Ritual', 'Practice 14 days in a row.', 'resistencia', 'Daily Streaks', 'plata', 14, 76),
  (77, 'streak_days_30', 'Lifestyle', 'Practice 30 days in a row.', 'resistencia', 'Daily Streaks', 'oro', 30, 77),
  (78, 'streak_days_60', 'Devotion', 'Practice 60 days in a row.', 'resistencia', 'Daily Streaks', 'oro', 60, 78),
  (79, 'streak_days_100', 'Unbreakable', 'Practice 100 days in a row.', 'resistencia', 'Daily Streaks', 'diamante', 100, 79),
  (80, 'streak_days_180', 'Monolith', 'Practice 180 days in a row.', 'resistencia', 'Daily Streaks', 'diamante', 180, 80),
  (81, 'streak_days_365', 'Ancestral Consistency', 'Practice 365 days in a row.', 'resistencia', 'Daily Streaks', 'especial', 365, 81),
  (82, 'total_sessions_10', 'Student', 'Complete 10 total sessions.', 'resistencia', 'Volume', 'bronce', 10, 82),
  (83, 'total_sessions_50', 'Apprentice', 'Complete 50 total sessions.', 'resistencia', 'Volume', 'bronce', 50, 83),
  (84, 'total_sessions_100', 'Practitioner', 'Complete 100 total sessions.', 'resistencia', 'Volume', 'plata', 100, 84),
  (85, 'total_sessions_250', 'Dedicated', 'Complete 250 total sessions.', 'resistencia', 'Volume', 'plata', 250, 85),
  (86, 'total_sessions_500', 'Veteran', 'Complete 500 total sessions.', 'resistencia', 'Volume', 'oro', 500, 86),
  (87, 'total_sessions_1000', 'Grand Master', 'Complete 1,000 total sessions.', 'resistencia', 'Volume', 'diamante', 1000, 87),
  (88, 'total_sessions_2500', 'Keyboard Immortal', 'Complete 2,500 total sessions.', 'resistencia', 'Volume', 'diamante', 2500, 88),
  (89, 'total_sessions_5000', 'Deity', 'Complete 5,000 total sessions.', 'resistencia', 'Volume', 'especial', 5000, 89),
  (90, 'endurance_typing_60min', 'Marathoner', 'Accumulate 1 hour of active typing (pauses under 30s).', 'resistencia', 'Marathon', 'oro', 60, 90),
  (91, 'endurance_keys_1m', 'Keystroke Millionaire', 'Reach 1,000,000 total correct keystrokes.', 'resistencia', 'Keystroke Volume', 'especial', 1000000, 91),
  (92, 'endurance_keys_100k', 'Hundred Thousand', 'Reach 100,000 total correct keystrokes.', 'resistencia', 'Keystroke Volume', 'oro', 100000, 92),
  (93, 'endurance_keys_10k', 'Ten Thousand Touches', 'Reach 10,000 total correct keystrokes.', 'resistencia', 'Keystroke Volume', 'bronce', 10000, 93),
  (94, 'music_same_artist_10', 'Fan', 'Play songs by the same artist 10 times.', 'musica', 'Artists', 'plata', 10, 94),
  (95, 'music_same_artist_25', 'Superfan', 'Play songs by the same artist 25 times.', 'musica', 'Artists', 'oro', 25, 95),
  (96, 'music_languages_3', 'Polyglot', 'Complete songs in 3 different languages.', 'musica', 'Languages', 'oro', 3, 96),
  (97, 'music_languages_5', 'Global Ambassador', 'Complete songs in 5 different languages.', 'musica', 'Languages', 'diamante', 5, 97),
  (98, 'music_full_lobby', 'Full Stadium', 'Complete a multiplayer song race in a full lobby.', 'musica', 'Music Lobbies', 'diamante', 1, 98),
  (99, 'rank_first_a', 'Seeking Perfection', 'Earn your first global A grade.', 'rangos', 'First Ranks', 'bronce', 1, 99),
  (100, 'rank_first_s', 'Elite', 'Earn your first global S grade.', 'rangos', 'First Ranks', 'plata', 1, 100),
  (101, 'rank_first_ss', 'Dvorak Master', 'Earn your first global SS grade.', 'rangos', 'First Ranks', 'oro', 1, 101),
  (102, 'rank_ascended', 'Ascended', 'Earn your first S+ or SS+ grade using hard modifiers.', 'rangos', 'First Ranks', 'diamante', 1, 102),
  (103, 'rank_gold_collector_50', 'Gold Collector', 'Accumulate 50 S-grade or better results in your history.', 'rangos', 'Rank Collection', 'diamante', 50, 103),
  (104, 'rank_gold_collector_100', 'Curator of Excellence', 'Accumulate 100 S-grade or better results in your history.', 'rangos', 'Rank Collection', 'especial', 100, 104)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  subcategory = excluded.subcategory,
  tier = excluded.tier,
  target_value = excluded.target_value,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('public.achievements_catalog', 'id'), (select coalesce(max(id), 1) from public.achievements_catalog));