-- Auto-generated from catalogData.ts
insert into public.achievements_catalog (id, slug, title, description, category, subcategory, tier, target_value, sort_order)
values
  (1, 'speed_wpm_30', 'Paseante', 'Alcanza 30 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'bronce', 30, 1),
  (2, 'speed_wpm_45', 'Trotador', 'Alcanza 45 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'bronce', 45, 2),
  (3, 'speed_wpm_60', 'Corredor', 'Alcanza 60 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'plata', 60, 3),
  (4, 'speed_wpm_75', 'Veloz', 'Alcanza 75 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'plata', 75, 4),
  (5, 'speed_wpm_90', 'Velocista', 'Alcanza 90 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'oro', 90, 5),
  (6, 'speed_wpm_105', 'Impulso', 'Alcanza 105 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'oro', 105, 6),
  (7, 'speed_wpm_120', 'Relámpago', 'Alcanza 120 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'diamante', 120, 7),
  (8, 'speed_wpm_135', 'Hipervelocidad', 'Alcanza 135 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'diamante', 135, 8),
  (9, 'speed_wpm_150', 'Supersónico', 'Alcanza 150 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'diamante', 150, 9),
  (10, 'speed_wpm_165', 'Fotón', 'Alcanza 165 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'diamante', 165, 10),
  (11, 'speed_wpm_180', 'Taquión', 'Alcanza 180 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'diamante', 180, 11),
  (12, 'speed_wpm_200', 'Singularidad Rítmica', 'Alcanza 200 WPM en una sesión.', 'velocidad', 'Picos de velocidad', 'especial', 200, 12),
  (13, 'speed_cruise_60', 'Velocidad de Crucero I', 'Mantén un WPM promedio superior a 60 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'plata', 60, 13),
  (14, 'speed_cruise_70', 'Velocidad de Crucero II', 'Mantén un WPM promedio superior a 70 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'plata', 70, 14),
  (15, 'speed_cruise_80', 'Velocidad de Crucero III', 'Mantén un WPM promedio superior a 80 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'oro', 80, 15),
  (16, 'speed_cruise_90', 'Velocidad de Crucero IV', 'Mantén un WPM promedio superior a 90 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'oro', 90, 16),
  (17, 'speed_cruise_100', 'Velocidad de Crucero V', 'Mantén un WPM promedio superior a 100 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'diamante', 100, 17),
  (18, 'speed_cruise_110', 'Velocidad de Crucero VI', 'Mantén un WPM promedio superior a 110 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'diamante', 110, 18),
  (19, 'speed_cruise_120', 'Velocidad de Crucero VII', 'Mantén un WPM promedio superior a 120 en una lección o canción completa.', 'velocidad', 'Velocidad sostenida', 'diamante', 120, 19),
  (20, 'speed_early_burst_100', 'Arranque Explosivo', 'Llega a 100 WPM en los primeros 5 segundos de una partida.', 'velocidad', 'Retos de velocidad', 'oro', 100, 20),
  (21, 'speed_sustain_80_300s', 'Motor Constante', 'Mantén 80+ WPM durante 5 minutos continuos en una sesión.', 'velocidad', 'Retos de velocidad', 'plata', 80, 21),
  (22, 'speed_peak_220', 'Horizonte de Eventos', 'Alcanza 220 WPM en una sesión (modo test).', 'velocidad', 'Retos de velocidad', 'especial', 220, 22),
  (23, 'perfect_sessions_1', 'Tiro Limpio', 'Completa 1 sesión con 100% de precisión.', 'precision', 'Sesiones perfectas', 'bronce', 1, 23),
  (24, 'perfect_sessions_5', 'Ojo de Águila', 'Completa 5 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'bronce', 5, 24),
  (25, 'perfect_sessions_10', 'Cirujano', 'Completa 10 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'plata', 10, 25),
  (26, 'perfect_sessions_25', 'Precisión Quirúrgica', 'Completa 25 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'plata', 25, 26),
  (27, 'perfect_sessions_50', 'Máquina', 'Completa 50 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'oro', 50, 27),
  (28, 'perfect_sessions_75', 'Automata', 'Completa 75 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'oro', 75, 28),
  (29, 'perfect_sessions_100', 'Perfección Absoluta', 'Completa 100 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'diamante', 100, 29),
  (30, 'perfect_sessions_250', 'Entidad Perfecta', 'Completa 250 sesiónes con 100% de precisión.', 'precision', 'Sesiones perfectas', 'especial', 250, 30),
  (31, 'combo_max_50', 'Concentración', 'Alcanza un combo de 50 teclas correctas seguidas.', 'precision', 'Combos', 'bronce', 50, 31),
  (32, 'combo_max_100', 'Cadena Sólida', 'Alcanza un combo de 100 teclas correctas seguidas.', 'precision', 'Combos', 'bronce', 100, 32),
  (33, 'combo_max_150', 'Flujo', 'Alcanza un combo de 150 teclas correctas seguidas.', 'precision', 'Combos', 'plata', 150, 33),
  (34, 'combo_max_200', 'Corriente', 'Alcanza un combo de 200 teclas correctas seguidas.', 'precision', 'Combos', 'plata', 200, 34),
  (35, 'combo_max_300', 'Trance', 'Alcanza un combo de 300 teclas correctas seguidas.', 'precision', 'Combos', 'oro', 300, 35),
  (36, 'combo_max_400', 'Estado Zen', 'Alcanza un combo de 400 teclas correctas seguidas.', 'precision', 'Combos', 'oro', 400, 36),
  (37, 'combo_max_500', 'Imparable', 'Alcanza un combo de 500 teclas correctas seguidas.', 'precision', 'Combos', 'diamante', 500, 37),
  (38, 'combo_max_750', 'Titán del Combo', 'Alcanza un combo de 750 teclas correctas seguidas.', 'precision', 'Combos', 'diamante', 750, 38),
  (39, 'combo_max_1000', 'Divino', 'Alcanza un combo de 1000 teclas correctas seguidas.', 'precision', 'Combos', 'especial', 1000, 39),
  (40, 'precision_steady_hand_5', 'Mano Firme', 'Juega 5 partidas consecutivas sin bajar del 98% de precisión.', 'precision', 'Consistencia', 'plata', 5, 40),
  (41, 'precision_steady_hand_10', 'Pulso de Acero', 'Juega 10 partidas consecutivas sin bajar del 98% de precisión.', 'precision', 'Consistencia', 'oro', 10, 41),
  (42, 'precision_recovery_100', 'Recuperación Rápida', 'Comete un error y levanta un combo de 100 teclas en la misma partida.', 'precision', 'Recuperación', 'oro', 100, 42),
  (43, 'precision_recovery_200', 'Fénix del Combo', 'Comete un error y levanta un combo de 200 teclas en la misma partida.', 'precision', 'Recuperación', 'diamante', 200, 43),
  (44, 'mp_wins_1', 'Contendiente', 'Gana 1 carrera multijugador.', 'multijugador', 'Victorias', 'bronce', 1, 44),
  (45, 'mp_wins_5', 'Rival', 'Gana 5 carreras multijugador.', 'multijugador', 'Victorias', 'bronce', 5, 45),
  (46, 'mp_wins_10', 'Gladiador', 'Gana 10 carreras multijugador.', 'multijugador', 'Victorias', 'plata', 10, 46),
  (47, 'mp_wins_25', 'Veterano de Arena', 'Gana 25 carreras multijugador.', 'multijugador', 'Victorias', 'plata', 25, 47),
  (48, 'mp_wins_50', 'Campeón', 'Gana 50 carreras multijugador.', 'multijugador', 'Victorias', 'oro', 50, 48),
  (49, 'mp_wins_100', 'Dominador', 'Gana 100 carreras multijugador.', 'multijugador', 'Victorias', 'diamante', 100, 49),
  (50, 'mp_wins_250', 'Conquistador', 'Gana 250 carreras multijugador.', 'multijugador', 'Victorias', 'diamante', 250, 50),
  (51, 'mp_wins_500', 'Leyenda', 'Gana 500 carreras multijugador.', 'multijugador', 'Victorias', 'especial', 500, 51),
  (52, 'mp_clutch_win', 'Clutch', 'Gana una carrera multijugador por una diferencia menor a 1 segundo.', 'multijugador', 'Hazañas de carrera', 'oro', 1, 52),
  (53, 'mp_dominant_win', 'Top Fragger', 'Gana una carrera superando al segundo lugar por más de 30 WPM.', 'multijugador', 'Hazañas de carrera', 'oro', 1, 53),
  (54, 'mp_grade_ss_win', 'Dominio Absoluto', 'Gana una carrera multijugador obteniendo rango SS o SS+.', 'multijugador', 'Hazañas de carrera', 'diamante', 1, 54),
  (55, 'mp_win_streak_5', 'Invicto', 'Gana 5 carreras multijugador consecutivas.', 'multijugador', 'Rachas de victoria', 'diamante', 5, 55),
  (56, 'mp_win_streak_10', 'Imparable en Red', 'Gana 10 carreras multijugador consecutivas.', 'multijugador', 'Rachas de victoria', 'especial', 10, 56),
  (57, 'mp_comeback_win', 'Remontada Épica', 'Pasa del último lugar en la primera mitad al primer lugar al terminar.', 'multijugador', 'Hazañas de carrera', 'especial', 1, 57),
  (58, 'mp_players_4', 'Sala Populosa', 'Completa una carrera multijugador con 4 o más jugadores.', 'multijugador', 'Salas multijugador', 'plata', 4, 58),
  (59, 'mp_players_8', 'Multitud', 'Completa una carrera multijugador con 8 jugadores.', 'multijugador', 'Salas multijugador', 'diamante', 8, 59),
  (60, 'mp_win_full_lobby', 'Rey de la Arena', 'Gana una carrera multijugador con 4 o más jugadores en la sala.', 'multijugador', 'Salas multijugador', 'oro', 1, 60),
  (61, 'mp_photo_finish', 'Foto Finish', 'Gana una carrera multijugador por menos de 0.5 segundos de diferencia.', 'multijugador', 'Hazañas de carrera', 'diamante', 1, 61),
  (62, 'mod_sudden_death_win', 'Viviendo al Límite', 'Gana una partida con Sudden Death activado.', 'riesgo', 'Modificadores', 'oro', 1, 62),
  (63, 'mod_blind_95', 'Memoria Muscular Pura', 'Termina una partida en Blind Mode con más del 95% de precisión.', 'riesgo', 'Modificadores', 'oro', 95, 63),
  (64, 'mod_strict_grade_s', 'Teclado Inmisericorde', 'Completa una sesión con Strict (sin backspace) con rango S o superior.', 'riesgo', 'Modificadores', 'diamante', 1, 64),
  (65, 'mod_flashlight_complete', 'Visión de Túnel', 'Supera una carrera con el modificador Flashlight activado.', 'riesgo', 'Modificadores', 'plata', 1, 65),
  (66, 'mod_vampire_survive', 'Sobreviviente', 'Gana una partida en Vampire terminando con menos del 10% de vida.', 'riesgo', 'Modificadores', 'diamante', 1, 66),
  (67, 'mod_double_time_grade_a', 'Adrenalina', 'Completa una canción con Double Time con rango A o superior.', 'riesgo', 'Modificadores', 'oro', 1, 67),
  (68, 'mod_rhythm_lock_perfect', 'Metrónomo Humano', 'Completa una canción con Rhythm Lock sin romper el combo por desfase.', 'riesgo', 'Modificadores', 'diamante', 1, 68),
  (69, 'mod_masocore', 'Masocore', 'Termina una partida con Sudden Death, Blind Mode y Flashlight activos simultáneamente.', 'riesgo', 'Modificadores', 'especial', 1, 69),
  (70, 'tech_left_hand_perfect', 'Vocales Dominadas', '100% de precisión en las teclas de la mano izquierda (A, O, E, U, I) en una sesión completa.', 'tecnica', 'Técnica', 'oro', 1, 70),
  (71, 'tech_right_hand_perfect', 'Consonantes Letales', '100% de precisión en las teclas de la mano derecha en una sesión completa.', 'tecnica', 'Técnica', 'oro', 1, 71),
  (72, 'tech_dev_symbols_ss', 'Código Limpio', 'Completa la lección de símbolos de desarrollo con rango SS.', 'tecnica', 'Técnica', 'diamante', 1, 72),
  (73, 'tech_custom_code_s', 'SysAdmin', 'Termina una sesión de texto personalizado con código fuente real con rango S o superior.', 'tecnica', 'Técnica', 'oro', 1, 73),
  (74, 'streak_days_3', 'Hábito', 'Practica 3 días seguidos.', 'resistencia', 'Rachas diarias', 'bronce', 3, 74),
  (75, 'streak_days_7', 'Disciplina', 'Practica 7 días seguidos.', 'resistencia', 'Rachas diarias', 'plata', 7, 75),
  (76, 'streak_days_14', 'Ritual', 'Practica 14 días seguidos.', 'resistencia', 'Rachas diarias', 'plata', 14, 76),
  (77, 'streak_days_30', 'Estilo de Vida', 'Practica 30 días seguidos.', 'resistencia', 'Rachas diarias', 'oro', 30, 77),
  (78, 'streak_days_60', 'Devoción', 'Practica 60 días seguidos.', 'resistencia', 'Rachas diarias', 'oro', 60, 78),
  (79, 'streak_days_100', 'Inquebrantable', 'Practica 100 días seguidos.', 'resistencia', 'Rachas diarias', 'diamante', 100, 79),
  (80, 'streak_days_180', 'Monolito', 'Practica 180 días seguidos.', 'resistencia', 'Rachas diarias', 'diamante', 180, 80),
  (81, 'streak_days_365', 'Constancia Ancestral', 'Practica 365 días seguidos.', 'resistencia', 'Rachas diarias', 'especial', 365, 81),
  (82, 'total_sessions_10', 'Estudiante', 'Completa 10 sesiones totales.', 'resistencia', 'Volumen', 'bronce', 10, 82),
  (83, 'total_sessions_50', 'Aprendiz', 'Completa 50 sesiones totales.', 'resistencia', 'Volumen', 'bronce', 50, 83),
  (84, 'total_sessions_100', 'Practicante', 'Completa 100 sesiones totales.', 'resistencia', 'Volumen', 'plata', 100, 84),
  (85, 'total_sessions_250', 'Dedicado', 'Completa 250 sesiones totales.', 'resistencia', 'Volumen', 'plata', 250, 85),
  (86, 'total_sessions_500', 'Veterano', 'Completa 500 sesiones totales.', 'resistencia', 'Volumen', 'oro', 500, 86),
  (87, 'total_sessions_1000', 'Gran Maestro', 'Completa 1000 sesiones totales.', 'resistencia', 'Volumen', 'diamante', 1000, 87),
  (88, 'total_sessions_2500', 'Inmortal del Teclado', 'Completa 2500 sesiones totales.', 'resistencia', 'Volumen', 'diamante', 2500, 88),
  (89, 'total_sessions_5000', 'Deidad', 'Completa 5000 sesiones totales.', 'resistencia', 'Volumen', 'especial', 5000, 89),
  (90, 'endurance_typing_60min', 'Maratonista', 'Acumula 1 hora de tecleo activo continuo (pausas menores a 30s).', 'resistencia', 'Maratón', 'oro', 60, 90),
  (91, 'endurance_keys_1m', 'Millonario de Teclas', 'Alcanza 1,000,000 de pulsaciones correctas totales acumuladas.', 'resistencia', 'Volumen de teclas', 'especial', 1000000, 91),
  (92, 'endurance_keys_100k', 'Centena de Miles', 'Alcanza 100,000 pulsaciones correctas totales.', 'resistencia', 'Volumen de teclas', 'oro', 100000, 92),
  (93, 'endurance_keys_10k', 'Diez Mil Toques', 'Alcanza 10,000 pulsaciones correctas totales.', 'resistencia', 'Volumen de teclas', 'bronce', 10000, 93),
  (94, 'music_same_artist_10', 'Fanático', 'Juega canciones del mismo artista 10 veces.', 'musica', 'Artistas', 'plata', 10, 94),
  (95, 'music_same_artist_25', 'Superfan', 'Juega canciones del mismo artista 25 veces.', 'musica', 'Artistas', 'oro', 25, 95),
  (96, 'music_languages_3', 'Políglota', 'Completa canciones en 3 idiomas diferentes.', 'musica', 'Idiomas', 'oro', 3, 96),
  (97, 'music_languages_5', 'Embajador Global', 'Completa canciones en 5 idiomas diferentes.', 'musica', 'Idiomas', 'diamante', 5, 97),
  (98, 'music_full_lobby', 'Estadio Lleno', 'Completa una carrera multijugador en modo canción en una sala llena.', 'musica', 'Salas musicales', 'diamante', 1, 98),
  (99, 'rank_first_a', 'Buscando la Perfección', 'Obtén tu primer rango A global.', 'rangos', 'Primeros rangos', 'bronce', 1, 99),
  (100, 'rank_first_s', 'Élite', 'Obtén tu primer rango S global.', 'rangos', 'Primeros rangos', 'plata', 1, 100),
  (101, 'rank_first_ss', 'Maestro Dvorak', 'Obtén tu primer rango SS global.', 'rangos', 'Primeros rangos', 'oro', 1, 101),
  (102, 'rank_ascended', 'Ascendido', 'Obtén tu primer rango S+ o SS+ usando modificadores difíciles.', 'rangos', 'Primeros rangos', 'diamante', 1, 102),
  (103, 'rank_gold_collector_50', 'Coleccionista de Oro', 'Acumula 50 rangos S o superiores en tu historial general.', 'rangos', 'Colección de rangos', 'diamante', 50, 103),
  (104, 'rank_gold_collector_100', 'Curador de Excelencia', 'Acumula 100 rangos S o superiores en tu historial general.', 'rangos', 'Colección de rangos', 'especial', 100, 104)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  subcategory = excluded.subcategory,
  tier = excluded.tier,
  target_value = excluded.target_value,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('public.achievements_catalog', 'id'), (select coalesce(max(id), 1) from public.achievements_catalog));